# Generated by Django 4.2.7 on 2025-08-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_deleted_at_category_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='walletaccount',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
