# Generated by Django 4.2.7 on 2025-08-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_category_options_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='originated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
